#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-JSON-MaybeXS
Version  : 1.004003
Release  : 21
URL      : https://cpan.metacpan.org/authors/id/E/ET/ETHER/JSON-MaybeXS-1.004003.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/ET/ETHER/JSON-MaybeXS-1.004003.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libj/libjson-maybexs-perl/libjson-maybexs-perl_1.004000-1.debian.tar.xz
Summary  : 'Use L<Cpanel::JSON::XS> with a fallback to L<JSON::XS> and L<JSON::PP>'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-JSON-MaybeXS-license = %{version}-%{release}
Requires: perl-JSON-MaybeXS-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Cpanel::JSON::XS)
BuildRequires : perl(Test::Needs)

%description
NAME
JSON::MaybeXS - Use Cpanel::JSON::XS with a fallback to JSON::XS and
JSON::PP

%package dev
Summary: dev components for the perl-JSON-MaybeXS package.
Group: Development
Provides: perl-JSON-MaybeXS-devel = %{version}-%{release}
Requires: perl-JSON-MaybeXS = %{version}-%{release}

%description dev
dev components for the perl-JSON-MaybeXS package.


%package license
Summary: license components for the perl-JSON-MaybeXS package.
Group: Default

%description license
license components for the perl-JSON-MaybeXS package.


%package perl
Summary: perl components for the perl-JSON-MaybeXS package.
Group: Default
Requires: perl-JSON-MaybeXS = %{version}-%{release}

%description perl
perl components for the perl-JSON-MaybeXS package.


%prep
%setup -q -n JSON-MaybeXS-1.004003
cd %{_builddir}
tar xf %{_sourcedir}/libjson-maybexs-perl_1.004000-1.debian.tar.xz
cd %{_builddir}/JSON-MaybeXS-1.004003
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/JSON-MaybeXS-1.004003/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-JSON-MaybeXS
cp %{_builddir}/JSON-MaybeXS-1.004003/LICENSE %{buildroot}/usr/share/package-licenses/perl-JSON-MaybeXS/8f372b06a35afe677e873c9fd12758676b74ba03
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-JSON-MaybeXS/621207c55af2b8ebe185e795936418432215495f
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/JSON::MaybeXS.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-JSON-MaybeXS/621207c55af2b8ebe185e795936418432215495f
/usr/share/package-licenses/perl-JSON-MaybeXS/8f372b06a35afe677e873c9fd12758676b74ba03

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/JSON/MaybeXS.pm
